/* tslint:disable */
/* eslint-disable */
/**
 * Cozy Creator
 * Cozy Creator OpenAPI specification
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobRequest
 */
export interface JobRequest {
    /**
     * A map of model names (string) to their weights (integer)
     * @type {{ [key: string]: number; }}
     * @memberof JobRequest
     */
    models: { [key: string]: number; };
    /**
     * The random seed to be used for generation
     * @type {number}
     * @memberof JobRequest
     */
    randomSeed?: number;
    /**
     * Aspect ratio for the generated content
     * @type {string}
     * @memberof JobRequest
     */
    aspectRatio?: JobRequestAspectRatioEnum;
    /**
     * A positive prompt to guide the generation
     * @type {string}
     * @memberof JobRequest
     */
    positivePrompt: string;
    /**
     * A negative prompt to exclude certain elements
     * @type {string}
     * @memberof JobRequest
     */
    negativePrompt?: string;
    /**
     * The desired output format
     * @type {string}
     * @memberof JobRequest
     */
    outputFormat?: JobRequestOutputFormatEnum;
    /**
     * URL to send the generated output to (optional)
     * @type {string}
     * @memberof JobRequest
     */
    webhookUrl?: string;
}


/**
 * @export
 */
export const JobRequestAspectRatioEnum = {
    _219: '21/9',
    _169: '16/9',
    _43: '4/3',
    _11: '1/1',
    _34: '3/4',
    _916: '9/16',
    _921: '9/21'
} as const;
export type JobRequestAspectRatioEnum = typeof JobRequestAspectRatioEnum[keyof typeof JobRequestAspectRatioEnum];

/**
 * @export
 */
export const JobRequestOutputFormatEnum = {
    Jpg: 'jpg',
    Png: 'png',
    Webp: 'webp'
} as const;
export type JobRequestOutputFormatEnum = typeof JobRequestOutputFormatEnum[keyof typeof JobRequestOutputFormatEnum];


/**
 * Check if a given object implements the JobRequest interface.
 */
export function instanceOfJobRequest(value: object): value is JobRequest {
    if (!('models' in value) || value['models'] === undefined) return false;
    if (!('positivePrompt' in value) || value['positivePrompt'] === undefined) return false;
    return true;
}

export function JobRequestFromJSON(json: any): JobRequest {
    return JobRequestFromJSONTyped(json, false);
}

export function JobRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'models': json['models'],
        'randomSeed': json['random_seed'] == null ? undefined : json['random_seed'],
        'aspectRatio': json['aspect_ratio'] == null ? undefined : json['aspect_ratio'],
        'positivePrompt': json['positive_prompt'],
        'negativePrompt': json['negative_prompt'] == null ? undefined : json['negative_prompt'],
        'outputFormat': json['output_format'] == null ? undefined : json['output_format'],
        'webhookUrl': json['webhook_url'] == null ? undefined : json['webhook_url'],
    };
}

  export function JobRequestToJSON(json: any): JobRequest {
      return JobRequestToJSONTyped(json, false);
  }

  export function JobRequestToJSONTyped(value?: JobRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'models': value['models'],
        'random_seed': value['randomSeed'],
        'aspect_ratio': value['aspectRatio'],
        'positive_prompt': value['positivePrompt'],
        'negative_prompt': value['negativePrompt'],
        'output_format': value['outputFormat'],
        'webhook_url': value['webhookUrl'],
    };
}

