/* tslint:disable */
/* eslint-disable */
/**
 * Cozy Creator
 * Cozy Creator OpenAPI specification
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobStatus } from './JobStatus';
import {
    JobStatusFromJSON,
    JobStatusFromJSONTyped,
    JobStatusToJSON,
    JobStatusToJSONTyped,
} from './JobStatus';
import type { JobRequest } from './JobRequest';
import {
    JobRequestFromJSON,
    JobRequestFromJSONTyped,
    JobRequestToJSON,
    JobRequestToJSONTyped,
} from './JobRequest';

/**
 * 
 * @export
 * @interface JobResult
 */
export interface JobResult {
    /**
     * Unique identifier for the job
     * @type {string}
     * @memberof JobResult
     */
    id: string;
    /**
     * 
     * @type {JobStatus}
     * @memberof JobResult
     */
    status: JobStatus;
    /**
     * 
     * @type {JobRequest}
     * @memberof JobResult
     */
    input: JobRequest;
    /**
     * Map of model names to arrays of image URLs
     * @type {object}
     * @memberof JobResult
     */
    output: object;
    /**
     * 
     * @type {Date}
     * @memberof JobResult
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof JobResult
     */
    completedAt: Date;
}



/**
 * Check if a given object implements the JobResult interface.
 */
export function instanceOfJobResult(value: object): value is JobResult {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('input' in value) || value['input'] === undefined) return false;
    if (!('output' in value) || value['output'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('completedAt' in value) || value['completedAt'] === undefined) return false;
    return true;
}

export function JobResultFromJSON(json: any): JobResult {
    return JobResultFromJSONTyped(json, false);
}

export function JobResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobResult {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': JobStatusFromJSON(json['status']),
        'input': JobRequestFromJSON(json['input']),
        'output': json['output'],
        'createdAt': (new Date(json['created_at'])),
        'completedAt': (new Date(json['completed_at'])),
    };
}

  export function JobResultToJSON(json: any): JobResult {
      return JobResultToJSONTyped(json, false);
  }

  export function JobResultToJSONTyped(value?: JobResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': JobStatusToJSON(value['status']),
        'input': JobRequestToJSON(value['input']),
        'output': value['output'],
        'created_at': ((value['createdAt']).toISOString()),
        'completed_at': ((value['completedAt']).toISOString()),
    };
}

