/* tslint:disable */
/* eslint-disable */
/**
 * Cozy Creator
 * Cozy Creator OpenAPI specification
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobStatus } from './JobStatus';
import {
    JobStatusFromJSON,
    JobStatusFromJSONTyped,
    JobStatusToJSON,
    JobStatusToJSONTyped,
} from './JobStatus';

/**
 * 
 * @export
 * @interface JobStatusResponse
 */
export interface JobStatusResponse {
    /**
     * ID of the Job
     * @type {string}
     * @memberof JobStatusResponse
     */
    id: string;
    /**
     * 
     * @type {JobStatus}
     * @memberof JobStatusResponse
     */
    status: JobStatus;
}



/**
 * Check if a given object implements the JobStatusResponse interface.
 */
export function instanceOfJobStatusResponse(value: object): value is JobStatusResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function JobStatusResponseFromJSON(json: any): JobStatusResponse {
    return JobStatusResponseFromJSONTyped(json, false);
}

export function JobStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': JobStatusFromJSON(json['status']),
    };
}

  export function JobStatusResponseToJSON(json: any): JobStatusResponse {
      return JobStatusResponseToJSONTyped(json, false);
  }

  export function JobStatusResponseToJSONTyped(value?: JobStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': JobStatusToJSON(value['status']),
    };
}

