/* tslint:disable */
/* eslint-disable */
/**
 * Cozy Creator
 * Cozy Creator OpenAPI specification
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodeOutput
 */
export interface NodeOutput {
    [key: string]: object;
}

/**
 * Check if a given object implements the NodeOutput interface.
 */
export function instanceOfNodeOutput(value: object): value is NodeOutput {
    return true;
}

export function NodeOutputFromJSON(json: any): NodeOutput {
    return NodeOutputFromJSONTyped(json, false);
}

export function NodeOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeOutput {
    return json;
}

  export function NodeOutputToJSON(json: any): NodeOutput {
      return NodeOutputToJSONTyped(json, false);
  }

  export function NodeOutputToJSONTyped(value?: NodeOutput | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

