/* tslint:disable */
/* eslint-disable */
/**
 * Cozy Creator
 * Cozy Creator OpenAPI specification
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeneratedOutput
 */
export interface GeneratedOutput {
    /**
     * List of URLs where the generated images can be accessed
     * @type {Array<string>}
     * @memberof GeneratedOutput
     */
    urls?: Array<string>;
    /**
     * The model identifier used for the generated images
     * @type {string}
     * @memberof GeneratedOutput
     */
    model?: string;
}

/**
 * Check if a given object implements the GeneratedOutput interface.
 */
export function instanceOfGeneratedOutput(value: object): value is GeneratedOutput {
    return true;
}

export function GeneratedOutputFromJSON(json: any): GeneratedOutput {
    return GeneratedOutputFromJSONTyped(json, false);
}

export function GeneratedOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratedOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'urls': json['urls'] == null ? undefined : json['urls'],
        'model': json['model'] == null ? undefined : json['model'],
    };
}

  export function GeneratedOutputToJSON(json: any): GeneratedOutput {
      return GeneratedOutputToJSONTyped(json, false);
  }

  export function GeneratedOutputToJSONTyped(value?: GeneratedOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'urls': value['urls'],
        'model': value['model'],
    };
}

