/* tslint:disable */
/* eslint-disable */
/**
 * Cozy Creator
 * Cozy Creator OpenAPI specification
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadResponseData
 */
export interface UploadResponseData {
    /**
     * URL of the uploaded file
     * @type {string}
     * @memberof UploadResponseData
     */
    url?: string;
}

/**
 * Check if a given object implements the UploadResponseData interface.
 */
export function instanceOfUploadResponseData(value: object): value is UploadResponseData {
    return true;
}

export function UploadResponseDataFromJSON(json: any): UploadResponseData {
    return UploadResponseDataFromJSONTyped(json, false);
}

export function UploadResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

  export function UploadResponseDataToJSON(json: any): UploadResponseData {
      return UploadResponseDataToJSONTyped(json, false);
  }

  export function UploadResponseDataToJSONTyped(value?: UploadResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
    };
}

