/* tslint:disable */
/* eslint-disable */
/**
 * Cozy Creator
 * Cozy Creator OpenAPI specification
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Node } from './Node';
import {
    NodeFromJSON,
    NodeFromJSONTyped,
    NodeToJSON,
    NodeToJSONTyped,
} from './Node';

/**
 * 
 * @export
 * @interface Workflow
 */
export interface Workflow {
    /**
     * The unique identifier for the workflow
     * @type {string}
     * @memberof Workflow
     */
    id?: string;
    /**
     * A list of nodes involved in the workflow
     * @type {Array<Node>}
     * @memberof Workflow
     */
    nodes?: Array<Node>;
}

/**
 * Check if a given object implements the Workflow interface.
 */
export function instanceOfWorkflow(value: object): value is Workflow {
    return true;
}

export function WorkflowFromJSON(json: any): Workflow {
    return WorkflowFromJSONTyped(json, false);
}

export function WorkflowFromJSONTyped(json: any, ignoreDiscriminator: boolean): Workflow {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'nodes': json['nodes'] == null ? undefined : ((json['nodes'] as Array<any>).map(NodeFromJSON)),
    };
}

  export function WorkflowToJSON(json: any): Workflow {
      return WorkflowToJSONTyped(json, false);
  }

  export function WorkflowToJSONTyped(value?: Workflow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'nodes': value['nodes'] == null ? undefined : ((value['nodes'] as Array<any>).map(NodeToJSON)),
    };
}

