/* tslint:disable */
/* eslint-disable */
/**
 * Cozy Creator
 * Cozy Creator OpenAPI specification
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkflowResponse
 */
export interface WorkflowResponse {
    /**
     * The unique identifier for the workflow
     * @type {string}
     * @memberof WorkflowResponse
     */
    id?: string;
    /**
     * The current status of the workflow execution
     * @type {string}
     * @memberof WorkflowResponse
     */
    status?: string;
}

/**
 * Check if a given object implements the WorkflowResponse interface.
 */
export function instanceOfWorkflowResponse(value: object): value is WorkflowResponse {
    return true;
}

export function WorkflowResponseFromJSON(json: any): WorkflowResponse {
    return WorkflowResponseFromJSONTyped(json, false);
}

export function WorkflowResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

  export function WorkflowResponseToJSON(json: any): WorkflowResponse {
      return WorkflowResponseToJSONTyped(json, false);
  }

  export function WorkflowResponseToJSONTyped(value?: WorkflowResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
    };
}

