templateDir: ./typescript-client/templates
generateAliasAsModel: true
supportsES6: true
target: es2022
typescriptThreePlus: true
withInterfaces: true
# useSingleRequestParameter: true
files:
  client.mustache:
    templateType: SupportingFiles
    destinationFilename: client.ts