/* tslint:disable */
/* eslint-disable */
/**
 * Cozy Creator
 * Cozy Creator OpenAPI specification
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeneratedOutput
 */
export interface GeneratedOutput {
    /**
     * The generated output data (e.g., image file, etc.)
     * @type {Blob}
     * @memberof GeneratedOutput
     */
    data?: Blob;
}

/**
 * Check if a given object implements the GeneratedOutput interface.
 */
export function instanceOfGeneratedOutput(value: object): value is GeneratedOutput {
    return true;
}

export function GeneratedOutputFromJSON(json: any): GeneratedOutput {
    return GeneratedOutputFromJSONTyped(json, false);
}

export function GeneratedOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratedOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
    };
}

  export function GeneratedOutputToJSON(json: any): GeneratedOutput {
      return GeneratedOutputToJSONTyped(json, false);
  }

  export function GeneratedOutputToJSONTyped(value?: GeneratedOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
    };
}

