/* tslint:disable */
/* eslint-disable */
/**
 * Cozy Creator
 * Cozy Creator OpenAPI specification
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GeneratedOutput } from './GeneratedOutput';
import {
    GeneratedOutputFromJSON,
    GeneratedOutputFromJSONTyped,
    GeneratedOutputToJSON,
    GeneratedOutputToJSONTyped,
} from './GeneratedOutput';

/**
 * 
 * @export
 * @interface GenerationResponse
 */
export interface GenerationResponse {
    /**
     * The unique identifier for the generation request
     * @type {string}
     * @memberof GenerationResponse
     */
    id?: string;
    /**
     * The index of the current part of the response stream
     * @type {number}
     * @memberof GenerationResponse
     */
    index?: number;
    /**
     * The current status of the request
     * @type {string}
     * @memberof GenerationResponse
     */
    status?: string;
    /**
     * 
     * @type {GeneratedOutput}
     * @memberof GenerationResponse
     */
    output?: GeneratedOutput;
}

/**
 * Check if a given object implements the GenerationResponse interface.
 */
export function instanceOfGenerationResponse(value: object): value is GenerationResponse {
    return true;
}

export function GenerationResponseFromJSON(json: any): GenerationResponse {
    return GenerationResponseFromJSONTyped(json, false);
}

export function GenerationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'index': json['index'] == null ? undefined : json['index'],
        'status': json['status'] == null ? undefined : json['status'],
        'output': json['output'] == null ? undefined : GeneratedOutputFromJSON(json['output']),
    };
}

  export function GenerationResponseToJSON(json: any): GenerationResponse {
      return GenerationResponseToJSONTyped(json, false);
  }

  export function GenerationResponseToJSONTyped(value?: GenerationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'index': value['index'],
        'status': value['status'],
        'output': GeneratedOutputToJSON(value['output']),
    };
}

